import type { z } from 'zod';
import type { RpcResponse, RpcResult } from './common';
import type { broker, liquidityProvider, operator, unregistered, validator } from './parsers';

export type CfAccountInfo = RpcResult<'cf_account_info'>;
export type CfAccounts = RpcResult<'cf_accounts'>;
export type CfAuctionState = RpcResult<'cf_auction_state'>;
export type CfAvailablePools = RpcResult<'cf_available_pools'>;
export type CfBoostPoolDetails = RpcResult<'cf_boost_pool_details'>;
export type CfBoostPoolPendingFees = RpcResult<'cf_boost_pool_pending_fees'>;
export type CfBoostPoolsDepth = RpcResult<'cf_boost_pools_depth'>;
export type CfEncodeCfParameters = RpcResult<'cf_encode_cf_parameters'>;
export type CfEnvironment = RpcResult<'cf_environment'>;
export type CfFailedCallArbitrum = RpcResult<'cf_failed_call_arbitrum'>;
export type CfFailedCallEthereum = RpcResult<'cf_failed_call_ethereum'>;
export type CfFlipSupply = RpcResult<'cf_flip_supply'>;
export type CfFundingEnvironment = RpcResult<'cf_funding_environment'>;
export type CfGetTradingStrategies = RpcResult<'cf_get_trading_strategies'>;
export type CfGetTradingStrategyLimits = RpcResult<'cf_get_trading_strategy_limits'>;
export type CfIngressEgressEnvironment = RpcResult<'cf_ingress_egress_environment'>;
export type CfPoolDepth = RpcResult<'cf_pool_depth'>;
export type CfPoolOrderbook = RpcResult<'cf_pool_orderbook'>;
export type CfPoolOrders = RpcResult<'cf_pool_orders'>;
export type CfPoolPriceV2 = RpcResult<'cf_pool_price_v2'>;
export type CfPoolsEnvironment = RpcResult<'cf_pools_environment'>;
export type CfRequestSwapParameterEncoding = RpcResult<'cf_request_swap_parameter_encoding'>;
export type CfSafeModeStatuses = RpcResult<'cf_safe_mode_statuses'>;
export type CfSupportedAssets = RpcResult<'cf_supported_assets'>;
export type CfSwappingEnvironment = RpcResult<'cf_swapping_environment'>;
export type CfSwapRate = RpcResult<'cf_swap_rate'>;
export type CfSwapRateV2 = RpcResult<'cf_swap_rate_v2'>;
export type CfSwapRateV3 = RpcResult<'cf_swap_rate_v3'>;
export type CfOraclePrices = RpcResult<'cf_oracle_prices'>;
export type CfLendingPools = RpcResult<'cf_lending_pools'>;
export type CfLendingConfig = RpcResult<'cf_lending_config'>;

export type CfAccountInfoResponse = RpcResponse<'cf_account_info'>;
export type CfAccountsResponse = RpcResponse<'cf_accounts'>;
export type CfAuctionStateResponse = RpcResponse<'cf_auction_state'>;
export type CfAvailablePoolsResponse = RpcResponse<'cf_available_pools'>;
export type CfBoostPoolDetailsResponse = RpcResponse<'cf_boost_pool_details'>;
export type CfBoostPoolPendingFeesResponse = RpcResponse<'cf_boost_pool_pending_fees'>;
export type CfBoostPoolsDepthResponse = RpcResponse<'cf_boost_pools_depth'>;
export type CfEncodeCfParametersResponse = RpcResponse<'cf_encode_cf_parameters'>;
export type CfEnvironmentResponse = RpcResponse<'cf_environment'>;
export type CfFailedCallArbitrumResponse = RpcResponse<'cf_failed_call_arbitrum'>;
export type CfFailedCallEthereumResponse = RpcResponse<'cf_failed_call_ethereum'>;
export type CfFlipSupplyResponse = RpcResponse<'cf_flip_supply'>;
export type CfFundingEnvironmentResponse = RpcResponse<'cf_funding_environment'>;
export type CfGetTradingStrategiesResponse = RpcResponse<'cf_get_trading_strategies'>;
export type CfGetTradingStrategyLimitsResponse = RpcResponse<'cf_get_trading_strategy_limits'>;
export type CfIngressEgressEnvironmentResponse = RpcResponse<'cf_ingress_egress_environment'>;
export type CfPoolDepthResponse = RpcResponse<'cf_pool_depth'>;
export type CfPoolOrderbookResponse = RpcResponse<'cf_pool_orderbook'>;
export type CfPoolOrdersResponse = RpcResponse<'cf_pool_orders'>;
export type CfPoolPriceV2Response = RpcResponse<'cf_pool_price_v2'>;
export type CfPoolsEnvironmentResponse = RpcResponse<'cf_pools_environment'>;
export type CfRequestSwapParameterEncodingResponse =
  RpcResponse<'cf_request_swap_parameter_encoding'>;
export type CfSafeModeStatusesResponse = RpcResponse<'cf_safe_mode_statuses'>;
export type CfSupportedAssetsResponse = RpcResponse<'cf_supported_assets'>;
export type CfSwappingEnvironmentResponse = RpcResponse<'cf_swapping_environment'>;
export type CfSwapRateResponse = RpcResponse<'cf_swap_rate'>;
export type CfSwapRateV2Response = RpcResponse<'cf_swap_rate_v2'>;
export type CfSwapRateV3Response = RpcResponse<'cf_swap_rate_v3'>;
export type CfOraclePricesResponse = RpcResponse<'cf_oracle_prices'>;
export type CfLendingPoolsResponse = RpcResponse<'cf_lending_pools'>;
export type CfLendingConfigResponse = RpcResponse<'cf_lending_config'>;

export type CfUnregisteredAccount = z.output<typeof unregistered>;
export type CfBrokerAccount = z.output<typeof broker>;
export type CfValidatorAccount = z.output<typeof validator>;
export type CfLiquidityProviderAccount = z.output<typeof liquidityProvider>;
export type CfOperatorAccount = z.output<typeof operator>;

export type LpTotalBalances = RpcResult<'lp_total_balances'>;
export type LpTotalBalancesResponse = RpcResponse<'lp_total_balances'>;

export type { RpcLimitOrder, RpcRangeOrder } from './parsers';
export type { RpcMethod, RpcRequest as RpcParams, RpcResult } from './common';
